package com.boombustgroup.amorfati.engine.economics.firm

import com.boombustgroup.amorfati.agents.{Firm, Household}
import com.boombustgroup.amorfati.engine.ledger.LedgerFinancialState
import com.boombustgroup.amorfati.types.*

/** Flattened public firm-stage output consumed by downstream monthly calculus.
  */
final case class StepOutput(
    ioFirms: Vector[Firm.State],
    households: Vector[Household.State],
    sumTax: PLN,
    sumCapex: PLN,
    sumTechImp: PLN,
    sumNewLoans: PLN,
    automationTechCapex: PLN,
    automationTechImports: PLN,
    automationTechLoans: PLN,
    automationUpgradeFailures: Int,
    automationAiDebtTrap: Int,
    automationNewFullAi: Int,
    automationNewHybrid: Int,
    sumEquityIssuance: PLN,
    sumGrossInvestment: PLN,
    sumBondIssuance: PLN,
    sumProfitShifting: PLN,
    sumFdiRepatriation: PLN,
    sumInventoryChange: PLN,
    sumCitEvasion: PLN,
    sumEnergyCost: PLN,
    sumGreenInvestment: PLN,
    totalIoPaid: PLN,
    nplNew: PLN,
    nplLoss: PLN,
    totalBondDefault: PLN,
    firmDeaths: Int,
    intIncome: PLN,
    corpBondAbsorption: Share,
    actualBondIssuance: PLN,
    netMigration: Int,
    perBankNewLoans: Vector[PLN],
    sumFirmPrincipal: PLN,
    perBankFirmPrincipal: Vector[PLN],
    perBankNplDebt: Vector[PLN],
    perBankIntIncome: Vector[PLN],
    perBankWorkers: Vector[Int],
    lendingRates: Vector[Rate],
    sumInvestmentCreditDemand: PLN,
    sumInvestmentCreditApproved: PLN,
    sumInvestmentCreditRejected: PLN,
    sumTechCreditDemand: PLN,
    sumTechCreditApproved: PLN,
    sumTechCreditRejected: PLN,
    sumTechSelectedCreditDemand: PLN,
    sumTechSelectedCreditApproved: PLN,
    sumTechSelectedCreditRejected: PLN,
    sumTechCandidateCreditDemand: PLN,
    sumTechCandidateCreditApproved: PLN,
    sumTechCandidateCreditRejected: PLN,
    sumCreditRejectedByReason: Firm.CreditRejectionBreakdown,
    postFirmCrossSectorHires: Int,
    postFirmHires: Int,
    postFirmHireCapacity: Int,
    markupInflation: Rate,
    sumRealizedPostTaxProfit: PLN,
    sumStateOwnedPostTaxProfit: PLN,
    decisionTraces: Vector[Firm.DecisionTrace],
    ledgerFinancialState: LedgerFinancialState,
)

object StepOutput:
  def fromSections(
      state: FirmOutputState,
      flows: FirmOutputFlowTotals,
      automation: FirmOutputAutomationTotals,
      banking: FirmOutputBankingTotals,
      credit: FirmOutputCreditTotals,
      labor: FirmOutputLaborTotals,
      profitability: FirmOutputProfitability,
  ): StepOutput =
    StepOutput(
      ioFirms = state.ioFirms,
      households = state.households,
      sumTax = flows.sumTax,
      sumCapex = flows.sumCapex,
      sumTechImp = flows.sumTechImp,
      sumNewLoans = flows.sumNewLoans,
      automationTechCapex = automation.techCapex,
      automationTechImports = automation.techImports,
      automationTechLoans = automation.techLoans,
      automationUpgradeFailures = automation.upgradeFailures,
      automationAiDebtTrap = automation.aiDebtTrap,
      automationNewFullAi = automation.newFullAi,
      automationNewHybrid = automation.newHybrid,
      sumEquityIssuance = flows.sumEquityIssuance,
      sumGrossInvestment = flows.sumGrossInvestment,
      sumBondIssuance = flows.sumBondIssuance,
      sumProfitShifting = flows.sumProfitShifting,
      sumFdiRepatriation = flows.sumFdiRepatriation,
      sumInventoryChange = flows.sumInventoryChange,
      sumCitEvasion = flows.sumCitEvasion,
      sumEnergyCost = flows.sumEnergyCost,
      sumGreenInvestment = flows.sumGreenInvestment,
      totalIoPaid = flows.totalIoPaid,
      nplNew = banking.nplNew,
      nplLoss = banking.nplLoss,
      totalBondDefault = banking.totalBondDefault,
      firmDeaths = banking.firmDeaths,
      intIncome = banking.intIncome,
      corpBondAbsorption = banking.corpBondAbsorption,
      actualBondIssuance = banking.actualBondIssuance,
      netMigration = labor.netMigration,
      perBankNewLoans = banking.perBankNewLoans,
      sumFirmPrincipal = flows.sumFirmPrincipal,
      perBankFirmPrincipal = banking.perBankFirmPrincipal,
      perBankNplDebt = banking.perBankNplDebt,
      perBankIntIncome = banking.perBankIntIncome,
      perBankWorkers = banking.perBankWorkers,
      lendingRates = banking.lendingRates,
      sumInvestmentCreditDemand = credit.investmentDemand,
      sumInvestmentCreditApproved = credit.investmentApproved,
      sumInvestmentCreditRejected = credit.investmentRejected,
      sumTechCreditDemand = credit.techDemand,
      sumTechCreditApproved = credit.techApproved,
      sumTechCreditRejected = credit.techRejected,
      sumTechSelectedCreditDemand = credit.techSelectedDemand,
      sumTechSelectedCreditApproved = credit.techSelectedApproved,
      sumTechSelectedCreditRejected = credit.techSelectedRejected,
      sumTechCandidateCreditDemand = credit.techCandidateDemand,
      sumTechCandidateCreditApproved = credit.techCandidateApproved,
      sumTechCandidateCreditRejected = credit.techCandidateRejected,
      sumCreditRejectedByReason = credit.rejectedByReason,
      postFirmCrossSectorHires = labor.crossSectorHires,
      postFirmHires = labor.hires,
      postFirmHireCapacity = labor.hireCapacity,
      markupInflation = profitability.markupInflation,
      sumRealizedPostTaxProfit = profitability.realizedPostTaxProfit,
      sumStateOwnedPostTaxProfit = profitability.stateOwnedPostTaxProfit,
      decisionTraces = state.decisionTraces,
      ledgerFinancialState = state.ledgerFinancialState,
    )
