package com.boombustgroup.amorfati.montecarlo

import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

class McFirmDecisionTraceSchemaSpec extends AnyFlatSpec with Matchers:

  "McFirmDecisionTraceSchema" should "keep the firm decision trace header stable" in {
    McFirmDecisionTraceSchema.header shouldBe
      "RunId;Seed;Month;FirmId;OpeningTechState;ClosingTechState;DecisionType;BankruptcyReason;CashBefore;CashAfter;FirmLoanBefore;FirmLoanAfter;DigitalReadinessBefore;DigitalReadinessAfter;WorkersBefore;WorkersAfter;Capex;NewLoan;DownPayment;BankId;LendingRate;SelectedBankApproval;SelectedBankApprovalProbability;SelectedBankApprovalRoll;SelectedBankRejectionReason;SelectedBankProjectedCar;SelectedBankMinCar;SelectedBankLcr;SelectedBankLcrMin;SelectedBankNsfr;SelectedBankNsfrMin;FullAiFeasible;HybridFeasible;FullAiAdoptionProbability;HybridAdoptionProbability;AdoptionRoll;FullAiBankApproval;FullAiBankApprovalProbability;FullAiBankApprovalRoll;FullAiBankRejectionReason;FullAiBankProjectedCar;FullAiBankMinCar;FullAiBankLcr;FullAiBankLcrMin;FullAiBankNsfr;FullAiBankNsfrMin;HybridBankApproval;HybridBankApprovalProbability;HybridBankApprovalRoll;HybridBankRejectionReason;HybridBankProjectedCar;HybridBankMinCar;HybridBankLcr;HybridBankLcrMin;HybridBankNsfr;HybridBankNsfrMin;ImplementationFailureProbability;ImplementationRoll;UpgradeEfficiencyDraw;UpgradeEfficiencyMultiplier;InvestmentCreditNeed;InvestmentCreditAmount;InvestmentBankApproval;InvestmentBankApprovalProbability;InvestmentBankApprovalRoll;InvestmentBankRejectionReason;InvestmentBankProjectedCar;InvestmentBankMinCar;InvestmentBankLcr;InvestmentBankLcrMin;InvestmentBankNsfr;InvestmentBankNsfrMin;DigitalInvestProbability;DigitalInvestRoll;LaborAdjustmentResidualProbability;LaborAdjustmentResidualRoll"
  }
