package com.boombustgroup.amorfati.engine.economics.firm

import com.boombustgroup.amorfati.agents.Firm
import com.boombustgroup.amorfati.types.*

/** Accumulated monetary and credit-audit flows emitted by firm processing. */
private[firm] final case class FirmFlows(
    tax: PLN,
    capex: PLN,
    techImp: PLN,
    newLoans: PLN,
    equityIssuance: PLN,
    grossInvestment: PLN,
    bondIssuance: PLN,
    profitShifting: PLN,
    fdiRepatriation: PLN,
    inventoryChange: PLN,
    citEvasion: PLN,
    energyCost: PLN,
    greenInvestment: PLN,
    principalRepaid: PLN,
    investmentCreditDemand: PLN,
    investmentCreditApproved: PLN,
    investmentCreditRejected: PLN,
    techCreditDemand: PLN,
    techCreditApproved: PLN,
    techCreditRejected: PLN,
    techSelectedCreditDemand: PLN,
    techSelectedCreditApproved: PLN,
    techSelectedCreditRejected: PLN,
    techCandidateCreditDemand: PLN,
    techCandidateCreditApproved: PLN,
    techCandidateCreditRejected: PLN,
    creditRejectedByReason: Firm.CreditRejectionBreakdown,
):
  def +(o: FirmFlows): FirmFlows = FirmFlows(
    tax + o.tax,
    capex + o.capex,
    techImp + o.techImp,
    newLoans + o.newLoans,
    equityIssuance + o.equityIssuance,
    grossInvestment + o.grossInvestment,
    bondIssuance + o.bondIssuance,
    profitShifting + o.profitShifting,
    fdiRepatriation + o.fdiRepatriation,
    inventoryChange + o.inventoryChange,
    citEvasion + o.citEvasion,
    energyCost + o.energyCost,
    greenInvestment + o.greenInvestment,
    principalRepaid + o.principalRepaid,
    investmentCreditDemand + o.investmentCreditDemand,
    investmentCreditApproved + o.investmentCreditApproved,
    investmentCreditRejected + o.investmentCreditRejected,
    techCreditDemand + o.techCreditDemand,
    techCreditApproved + o.techCreditApproved,
    techCreditRejected + o.techCreditRejected,
    techSelectedCreditDemand + o.techSelectedCreditDemand,
    techSelectedCreditApproved + o.techSelectedCreditApproved,
    techSelectedCreditRejected + o.techSelectedCreditRejected,
    techCandidateCreditDemand + o.techCandidateCreditDemand,
    techCandidateCreditApproved + o.techCandidateCreditApproved,
    techCandidateCreditRejected + o.techCandidateCreditRejected,
    creditRejectedByReason + o.creditRejectedByReason,
  )

private[firm] object FirmFlows:
  val zero: FirmFlows = FirmFlows(
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    PLN.Zero,
    Firm.CreditRejectionBreakdown.zero,
  )
